const cart = [
  {
    id: 1,
    img: "images-2.jpg",
    title: "Komplekt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "xalat",
    price: 55000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 2,
    img: "img-sar.png",
    title: "Sariq jemfer",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "sariq-j",
    price: 79000.0,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 3,
    img: "img-ooq.png",
    title: "Oq jemfer",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "oq-jem",
    price: 29088,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 4,
    img: "img-sum.png",
    title: "Sumka",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "sumka",
    price: 29000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 5,
    img: "img-qor2.png",
    title: "Qora jemfer",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "qora-j",
    price: 79000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 6,
    img: "img-oq.png",
    title: "Oq xalat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "oq-xal",
    price: 27700,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 7,
    img: "img-oq.png",
    title: "Halat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "xalat",
    price: 88000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 8,
    img: "img-black.png",
    title: "Jemfir",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "qalin-j",
    price: 59700,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 9,
    img: "image-5.jpg",
    title: "Halat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "xalat",
    price: 81000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 10,
    img: "image-6.jpg",
    title: "Halat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "xalat",
    price: 55000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 11,
    img: "image-7.jpg",
    title: "Halat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "sariq-j",
    price: 77900,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 12,
    img: "images-1.jpg",
    title: "Do`kon",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "oq-xal",
    price: 829000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 13,
    img: "images-3.jpg",
    title: "Rubashkalar",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "oq-xal",
    price: 879000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 14,
    img: "images-4.jpg",
    title: "Koftalar",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "qora-j",
    price: 289000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 15,
    img: "images-5.jpg",
    title: "Moda do`kon",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "qalin-j",
    price: 899000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 16,
    img: "images-7.jpg",
    title: "Ko`ylaklar",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "qora-j",
    price: 889000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 17,
    img: "images-6.jpg",
    title: "Oq ko`ylaklar",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "qalin-j",
    price: 859000,
    count: 0,
    priceTotal: 0,
  },
  {
    id: 18,
    img: "images-7.webp",
    title: "Women shop",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    category: "oq-jem",
    price: 879000,
    count: 0,
    priceTotal: 0,
  },
];

export default cart;
